FROM microsoft/nanoserver:10.0.14393.1884

ADD https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz /usr/local
RUN xz -d -c /usr/local/upx-3.96-amd64_linux.tar.xz | tar -xOf - upx-3.96-amd64_linux/upx > /bin/upx && \
    chmod a+x /bin/upx

COPY drone-upx.exe /drone-upx.exe

ENTRYPOINT [ "\\drone-upx.exe" ]
