FROM plugins/base:linux-arm64

ADD https://github.com/upx/upx/releases/download/v3.96/upx-3.96-arm64_linux.tar.xz /usr/local
RUN xz -d -c /usr/local/upx-3.96-arm64_linux.tar.xz | tar -xOf - upx-3.96-arm64_linux/upx > /bin/upx && \
    chmod a+x /bin/upx

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

COPY release/linux/arm64/drone-upx /bin/
ENTRYPOINT ["/bin/drone-upx"]
