FROM plugins/base:linux-arm

ADD https://github.com/upx/upx/releases/download/v4.0.0/upx-4.0.0-arm_linux.tar.xz /usr/local
RUN xz -d -c /usr/local/upx-4.0.0-arm_linux.tar.xz | tar -xOf - upx-4.0.0-arm_linux/upx > /bin/upx && \
    chmod a+x /bin/upx

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

COPY release/linux/arm/drone-upx /bin/
ENTRYPOINT ["/bin/drone-upx"]
